-- seed.sql — intentionally seeds NO event data.
--
-- This file used to insert four Phase-1 demo events (Zubida Provincial Youth
-- Camp, ICON: Ignite Conference, Christian Life Seminar — Labangan, Household
-- Leaders' Formation). They were invented for the showcase build: the venues,
-- the slot counts, the picsum.photos covers, and the "all 26 chapters" claim
-- have no source (ZUBIDA_CONTENT_AUDIT.md §2.4).
--
-- While `getEvents()` still fell back to the same mock list, they read as
-- placeholders. Once the fallback was removed, these rows became the only thing
-- `/events` could serve — genuine database records, with a working Register
-- button, that a visitor cannot distinguish from a real event. Migration 0019
-- retires the rows; emptying this file stops them coming back on the next
-- `db:migrate` against any environment.
--
-- Events are records, not chrome. An empty schedule is a truthful schedule, and
-- the honest empty state already exists. Real events belong in /admin/events.
--
-- If a future environment genuinely needs fixture data, add it behind an
-- explicit flag — never to the default path.

select 1 where false;
